<a href="https://colab.research.google.com/github/saranyareddy77/MDS-LAB/blob/main/week_3%2C4%2C5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Most Streamed Artists on Spotify (17_07_2026) V1.1.csv')

In [5]:
# Display the first 5 rows of the DataFrame
display(df.head(10))

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970
5,Ariana Grande,Female,United States,English,Pop,Solo,2013,68298.9,57097.5,11201.4,41615.5,60.931435,26683.4,39.068565
6,Travis Scott,Male,United States,English,Hip-Hop,Solo,2013,65349.7,35338.7,30027.0,25309.9,38.729941,40039.8,61.270059
7,Kanye West,Male,United States,English,Hip-Hop,Solo,2004,65142.9,46558.4,18584.5,28473.0,43.708524,36669.9,56.291476
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,2011,64656.9,57704.0,6967.8,46700.0,72.227403,17956.9,27.772597
9,Eminem,Male,United States,English,Hip-Hop,Solo,1996,64549.0,54466.8,10100.7,32940.0,51.031000,31609.0,48.969000

In [6]:
display(df.tail(10))

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
490,JID,Male,United States,English,Hip-Hop,Solo,2010,7073.7,2882.3,4191.4,1158.3,16.374740,5915.4,83.625260
491,YNW Melly,Male,United States,English,Hip-Hop,Solo,2017,7061.3,7067.3,0.0,4346.8,61.558070,2714.5,38.441930
492,Juan Gabriel,Male,Mexico,Spanish,Latin,Solo,1971,7059.2,6505.8,557.1,5676.3,80.409961,1382.9,19.590039
493,Los Temerarios,Male,Mexico,Spanish,Latin,Group,1977,7059.2,6607.2,446.9,7059.2,100.000000,0.0,0.000000
494,Jason Mraz,Male,United States,English,Pop,Solo,2002,7048.5,6851.4,199.1,5805.0,82.357949,1243.5,17.642052
495,The Cure,Male,United Kingdom,English,Rock,Group,1979,7034.1,7035.0,3.3,6940.1,98.663653,94.0,1.336347
496,The Marías,Mixed,United States,English,Pop,Group,2017,7029.1,5774.4,1261.4,5705.9,81.175399,1323.2,18.824601
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,1997,7018.9,7018.4,5.4,6806.0,96.966761,212.9,3.033239
498,Korn,Male,United States,English,Metal,Group,1994,6976.4,4188.4,2798.5,6414.9,91.951436,561.5,8.048564
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,2017,6972.0,6956.0,20.3,1876.2,26.910499,5095.8,73.089501

In [7]:
# Display the shape of the DataFrame
print("DataFrame Shape:", df.shape)

DataFrame Shape: (500, 14)

In [8]:
# Display the index of the DataFrame
print("DataFrame Index:", df.index)

DataFrame Index: RangeIndex(start=0, stop=500, step=1)

In [9]:
# Display the columns of the DataFrame
print("DataFrame Columns:", df.columns)

DataFrame Columns: Index(['Artist Name', 'Sex', 'Country of Origin', 'Primary Language',
       'Primary Genre', ' Artist Type', 'Debut Year',
       'Total Streams (in millions)', 'Lead Streams (in millions)',
       'Feature Streams (in millions)', 'Solo Streams (in millions)',
       '% of Solo Streams', 'Collaborative Streams (in millions)',
       '% of Collaborative Streams'],
      dtype='object')

### Deleting Records (Rows) Based on a Condition

To delete rows that meet a specific condition, you can use boolean indexing. For example, let's delete all artists whose 'Sex' is 'Male' to demonstrate.

In [10]:
# Example: Delete rows where 'Sex' is 'Male'
original_rows = df.shape[0]
df_filtered_rows = df[df['Sex'] != 'Male'].copy()
print(f"Original number of rows: {original_rows}")
print(f"Number of rows after deleting 'Male' artists: {df_filtered_rows.shape[0]}")
display(df_filtered_rows.head())

Original number of rows: 500
Number of rows after deleting 'Male' artists: 110

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
5,Ariana Grande,Female,United States,English,Pop,Solo,2013,68298.9,57097.5,11201.4,41615.5,60.931435,26683.4,39.068565
10,Rihanna,Female,Barbados,English,Pop,Solo,2005,60670.7,44824.4,15846.4,30261.8,49.878772,30408.9,50.121228
11,Billie Eilish,Female,United States,English,Pop,Solo,2015,58049.5,57160.1,889.4,51567.9,88.834357,6481.6,11.165643
22,Nicki Minaj,Female,Trinidad and Tobago,English,Hip-Hop,Solo,2007,43330.3,16316.4,27027.9,9618.2,22.197400,33712.1,77.802600

### Deleting Columns

To delete columns, you can use the `drop()` method. Let's demonstrate by dropping the 'Debut Year' column.

In [11]:
# Example: Delete the 'Debut Year' column
original_columns = df.shape[1]
df_filtered_columns = df.drop(columns=['Debut Year']).copy()
print(f"Original number of columns: {original_columns}")
print(f"Number of columns after deleting 'Debut Year': {df_filtered_columns.shape[1]}")
display(df_filtered_columns.head())

Original number of columns: 14
Number of columns after deleting 'Debut Year': 13

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970

### Sorting Records

Let's sort the DataFrame by 'Total Streams (in millions)' in descending order to see the artists with the highest streams at the top. We'll create a new DataFrame `df_sorted` for this.

In [12]:
# Sort the DataFrame by 'Total Streams (in millions)' in descending order
df_sorted = df.sort_values(by='Total Streams (in millions)', ascending=False).copy()

print("DataFrame sorted by Total Streams (top 5):")
display(df_sorted.head())

DataFrame sorted by Total Streams (top 5):

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970

### Ranking Records

Now, let's add a new column named 'Stream Rank' to the DataFrame, ranking artists based on their 'Total Streams (in millions)'. We'll use the `df_sorted` DataFrame for this to apply rank on already sorted data.

In [13]:
# Add a 'Stream Rank' column based on 'Total Streams (in millions)'
df_ranked = df_sorted.copy()
df_ranked['Stream Rank'] = df_ranked['Total Streams (in millions)'].rank(ascending=False, method='min')

print("DataFrame with Stream Rank (top 5):")
display(df_ranked.head())

DataFrame with Stream Rank (top 5):

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams,Stream Rank
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754,1.0
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123,2.0
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914,3.0
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348,4.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970,5.0

### Descriptive Statistics for Numerical Columns

Let's get a summary of the central tendency, dispersion, and shape of the distribution of numerical columns using `df.describe()`.

In [14]:
# Display descriptive statistics for numerical columns
display(df.describe())

,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2005.346000,16817.610200,12141.734000,4681.289000,8324.397600,50.613084,8493.212600,49.386916
std,13.312578,14845.197632,11844.675186,5952.827762,9589.010168,33.762147,9612.491536,33.762147
min,1939.000000,6972.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2001.750000,8768.175000,6489.750000,696.500000,2519.775000,20.117951,2015.650000,16.860219
50%,2009.000000,11923.250000,8716.350000,3005.600000,6472.950000,47.062829,6592.250000,52.937171
75%,2014.000000,18020.050000,13456.900000,6093.350000,10115.550000,83.139781,11019.575000,79.882049
max,2023.000000,137492.100000,126177.300000,43710.500000,113421.500000,100.000000,84168.200000,100.000000

### Value Counts for a Categorical Column

Now, let's examine the distribution of a categorical column, for example, 'Primary Genre', using `value_counts()`.

In [15]:
# Display value counts for 'Primary Genre'
print("Value counts for 'Primary Genre':")
display(df['Primary Genre'].value_counts())

Value counts for 'Primary Genre':

Primary Genre
Hip-Hop             115
Pop                 102
Rock                 60
Reggaeton            43
R&B                  31
Latin                30
EDM                  22
Regional Mexican     19
K-Pop                11
Filmi                11
Country              10
Alternative           9
Sertanjeo             9
Metal                 8
Folk                  4
Soundtrack            3
Bachata               3
Soul                  3
Reggae                2
Afrobeats             2
Spoken Word           1
Children's Music      1
Nu Metal              1
Name: count, dtype: int64

### Mean, Median, and Mode for a Specific Numerical Column

Let's calculate the mean, median, and mode for 'Total Streams (in millions)' to understand its central tendency.

In [16]:
# Calculate mean, median, and mode for 'Total Streams (in millions)'
mean_streams = df['Total Streams (in millions)'].mean()
median_streams = df['Total Streams (in millions)'].median()
mode_streams = df['Total Streams (in millions)'].mode()

print(f"Mean of Total Streams (in millions): {mean_streams:.2f}")
print(f"Median of Total Streams (in millions): {median_streams:.2f}")
print(f"Mode of Total Streams (in millions): {mode_streams.tolist()}")

Mean of Total Streams (in millions): 16817.61
Median of Total Streams (in millions): 11923.25
Mode of Total Streams (in millions): [7059.2]

### Unique Values and Number of Unique Values for a Categorical Column

Let's find the unique entries and the total number of unique entries in a categorical column like 'Primary Genre'.

In [17]:
# Display unique values for 'Primary Genre'
print("Unique values for 'Primary Genre':")
display(df['Primary Genre'].unique())

Unique values for 'Primary Genre':

array(['Hip-Hop', 'Pop', 'Reggaeton', 'R&B', 'K-Pop', 'Rock',
       'Alternative', 'EDM', 'Filmi', 'Latin', 'Regional Mexican',
       'Country', 'Spoken Word', 'Soundtrack', 'Bachata', 'Sertanjeo',
       'Reggae', 'Folk', 'Metal', 'Afrobeats', 'Soul', "Children's Music",
       'Nu Metal'], dtype=object)

In [18]:
# Display the number of unique values for 'Primary Genre'
print("Number of unique values for 'Primary Genre':")
display(df['Primary Genre'].nunique())

Number of unique values for 'Primary Genre':

23

### Reconfirming Value Counts for 'Primary Genre'

Let's also reconfirm the value counts for 'Primary Genre' to see the distribution again.

In [19]:
# Display value counts for 'Primary Genre'
print("Value counts for 'Primary Genre':")
display(df['Primary Genre'].value_counts())

Value counts for 'Primary Genre':

Primary Genre
Hip-Hop             115
Pop                 102
Rock                 60
Reggaeton            43
R&B                  31
Latin                30
EDM                  22
Regional Mexican     19
K-Pop                11
Filmi                11
Country              10
Alternative           9
Sertanjeo             9
Metal                 8
Folk                  4
Soundtrack            3
Bachata               3
Soul                  3
Reggae                2
Afrobeats             2
Spoken Word           1
Children's Music      1
Nu Metal              1
Name: count, dtype: int64

### Renaming a Single Column

To rename a single column, we can use the `.rename()` method with a dictionary mapping the old column name to the new column name. Let's rename 'Artist Name' to 'Artist'.

In [20]:
# Rename a single column: 'Artist Name' to 'Artist'
df_single_renamed = df.rename(columns={'Artist Name': 'Artist'}).copy()

print("DataFrame with 'Artist Name' renamed to 'Artist' (first 5 rows):")
display(df_single_renamed.head())

DataFrame with 'Artist Name' renamed to 'Artist' (first 5 rows):

,Artist,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970

### Renaming Multiple Columns

We can also rename multiple columns at once by providing a dictionary with all the old-to-new column name mappings to the `.rename()` method. Let's rename 'Sex' to 'Gender' and 'Primary Language' to 'Language'.

In [21]:
# Rename multiple columns: 'Sex' to 'Gender' and 'Primary Language' to 'Language'
df_multi_renamed = df.rename(columns={'Sex': 'Gender', 'Primary Language': 'Language'}).copy()

print("DataFrame with 'Sex' renamed to 'Gender' and 'Primary Language' to 'Language' (first 5 rows):")
display(df_multi_renamed.head())

DataFrame with 'Sex' renamed to 'Gender' and 'Primary Language' to 'Language' (first 5 rows):

,Artist Name,Gender,Country of Origin,Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970

## Creating Pandas Series and DataFrames

Let's explore how to create Pandas Series and DataFrames from various Python data structures.

### Creating a Series from a List

A Pandas Series can be created from a simple Python list.

In [22]:
# Create a Series from a list
data_list = [10, 20, 30, 40, 50]
series_from_list = pd.Series(data_list)

print("Series created from a list:")
display(series_from_list)

Series created from a list:

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Creating a Series from a Dictionary

A Series can also be created from a Python dictionary, where keys become the index and values become the data.

In [23]:
# Create a Series from a dictionary
data_dict = {'a': 100, 'b': 200, 'c': 300}
series_from_dict = pd.Series(data_dict)

print("Series created from a dictionary:")
display(series_from_dict)

Series created from a dictionary:

a    100
b    200
c    300
dtype: int64

### Creating a DataFrame from a Dictionary of Lists

A common way to create a DataFrame is from a dictionary where each key represents a column name and its value is a list of data for that column.

In [24]:
# Create a DataFrame from a dictionary of lists
data_df_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df_from_dict_of_lists = pd.DataFrame(data_df_dict)

print("DataFrame created from a dictionary of lists:")
display(df_from_dict_of_lists)

DataFrame created from a dictionary of lists:

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston

### Creating a DataFrame from a List of Dictionaries

Another way to create a DataFrame is from a list where each dictionary in the list represents a row, and the keys are column names.

In [25]:
# Create a DataFrame from a list of dictionaries
data_df_list = [
    {'Name': 'Eve', 'Age': 22, 'City': 'Miami'},
    {'Name': 'Frank', 'Age': 40, 'City': 'Boston'},
    {'Name': 'Grace', 'Age': 33, 'City': 'Seattle'}
]
df_from_list_of_dicts = pd.DataFrame(data_df_list)

print("DataFrame created from a list of dictionaries:")
display(df_from_list_of_dicts)

DataFrame created from a list of dictionaries:

    Name  Age     City
0    Eve   22    Miami
1  Frank   40   Boston
2  Grace   33  Seattle